### ISSUE TITLE
Baleen Capital Debrief 12-16-15

### ISSUE THREAD

**Issue by chrisbiddy** [chrisbiddy/Investor-Interactions#2]
@bronwynagrios @kokorich

Bronwyn and myself had another call with Fang and Nick today to discuss the processing pipeline plans as well as the customer numbers (agreements, business model, revenue projections)

Some main points:
Our pricing model vs incumbents (order of magnitude lower cost than RapidEye comparing subscription plan to per image cost (RE))
Also highlighted minimum purchase for incumbents vs our flexible shape approach
Revenue "pipeline" is ~$200M (over 5 years) based on our estimates of market size for each prospective customer
Signed contracts ~$70M (over 5 years) with revenue figures derived from customer conversations of their expected market size
Fang asked how firm pricing model is and if projected revenue is calculated using this pricing model
Fang asked to play around with enterprise portion of the platform and was doing so in real time
Fang asked what percentage of total business would be from us for each customer in our pipeline and what percentage is based on commercial applications vs intelligence and security applications
Nick asked if we knew Quantum Spatial ($100M in revenue) and offered to introduce us
Conversation ended with Fang asking if he could talk with 3 of our customers (1 from Re-seller, Customer, and Platform) and ask 1) How are our technical capabilities and why do they want to work with us and 2) What is the overall market potential for their application(s), i.e. size of the commercial market
He also asked separate if he can talk to Manfred about us since he knows him (I said yes)

Final note: Fang started saying "our" prices and "our" data half way through the conversation, hopefully some insight into his thinking....

**Comment by bronwynagrios** [comment]
Reposted this into the team GitHub. Will comment there.

https://github.com/AstroDigital/fundraising/issues/2

On December 16, 2015 at 6:06:29 PM, chrisbiddy (notifications@github.com) wrote:

@bronwynagrios @kokorich

Bronwyn and myself had another call with Fang and Nick today to discuss the processing pipeline plans as well as the customer numbers (agreements, business model, revenue projections)

Some main points:
Our pricing model vs incumbents (order of magnitude lower cost than RapidEye comparing subscription plan to per image cost (RE))
Also highlighted minimum purchase for incumbents vs our flexible shape approach
Revenue "pipeline" is ~$200M (over 5 years) based on our estimates of market size for each prospective customer
Signed contracts ~$70M (over 5 years) with revenue figures derived from customer conversations of their expected market size
Fang asked how firm pricing model is and if projected revenue is calculated using this pricing model
Fang asked to play around with enterprise portion of the platform and was doing so in real time
Fang asked what percentage of total business would be from us for each customer in our pipeline and what percentage is based on commercial applications vs intelligence and security applications
Nick asked if we knew Quantum Spatial ($100M in revenue) and offered to introduce us
Conversation ended with Fang asking if he could talk with 3 of our customers (1 from Re-seller, Customer, and Platform) and ask 1) How are our technical capabilities and why do they want to work with us and 2) What is the overall market potential for their application(s), i.e. size of the commercial market
He also asked separate if he can talk to Manfred about us since he knows him (I said yes)

Final note: Fang started saying "our" prices and "our" data half way through the conversation, hopefully some insight into his thinking....
